version: '3.8'
services:
  neo4j:
    image: neo4j:5.26.8
    container_name: neo4j
    ports:
      - 7474:7474  # HTTP (Browser UI)
      - 7687:7687  # Bolt (Cypher query)
    environment:
      - NEO4J_AUTH=neo4j/testpassword
    volumes:
      - neo4j-data:/data
      - ..:/workspace

volumes:
  neo4j-data: